objs=[
  {"neg_ok"=>false, "pvalues_desc"=>"Scroll,Fixed", "default_value"=>0, "pvalues"=>"scroll,fixed", "punits"=>"", "title"=>"background-attachment", "id"=>1, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"transparent,aqua,black,blue,fuchsia,gray,green,lime,maroon,navy,olive,purple,red,silver,teal,white,yellow,0c", "default_value"=>0, "pvalues"=>"transparent,aqua,black,blue,fuchsia,gray,green,lime,maroon,navy,olive,purple,red,silver,teal,white,yellow,0c", "punits"=>"", "title"=>"background-color", "id"=>2, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"None,0i", "default_value"=>0, "pvalues"=>"none,0i", "punits"=>"", "title"=>"background-image", "id"=>3, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Left|top,Center|center,Right|bottom,L1|l1", "default_value"=>0, "pvalues"=>"left|top,center|center,right|bottom,l1|l1", "punits"=>"l,%", "title"=>"background-position", "id"=>4, "pvspecial"=>"hv"},
  {"neg_ok"=>false, "pvalues_desc"=>"Repeat,Repeat-x,Repeat-y,No-repeat", "default_value"=>0, "pvalues"=>"repeat,repeat-x,repeat-y,no-repeat", "punits"=>"", "title"=>"background-repeat", "id"=>5, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Transparent,Aqua,Black,Blue,Fuchsia,Gray,Green,Lime,Maroon,Navy,Olive,Purple,Red,Silver,Teal,White,Yellow,0c", "default_value"=>-1, "pvalues"=>"transparent,aqua,black,blue,fuchsia,gray,green,lime,maroon,navy,olive,purple,red,silver,teal,white,yellow,0c", "punits"=>"hex,rgb", "title"=>"border-color", "id"=>6, "pvspecial"=>"trbl"},
  {"neg_ok"=>false, "pvalues_desc"=>"None,Double,Solid,Dashed,Dotted,Ridge,Outset,Groove,Inset", "default_value"=>0, "pvalues"=>"none,double,solid,dashed,dotted,ridge,outset,groove,inset", "punits"=>"", "title"=>"border-style", "id"=>7, "pvspecial"=>"trbl"},
  {"neg_ok"=>false, "pvalues_desc"=>"L1", "default_value"=>0, "pvalues"=>"l1", "punits"=>"l", "title"=>"border-width", "id"=>8, "pvspecial"=>"trbl"},
  {"neg_ok"=>false, "pvalues_desc"=>"None,Left,Right,Both", "default_value"=>0, "pvalues"=>"none,left,right,both", "punits"=>"", "title"=>"clear", "id"=>9, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Auto,Default,Crosshair,Pointer,Move,N-resize,Ne-resize,E-resize,Se-resize,S-resize,Sw-resize,W-resize,Nw-resize,Text,Wait,Help", "default_value"=>0, "pvalues"=>"auto,default,crosshair,pointer,move,n-resize,ne-resize,e-resize,se-resize,s-resize,sw-resize,w-resize,nw-resize,text,wait,help", "punits"=>"", "title"=>"cursor", "id"=>10, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Inline,None,Block,List-item,Run-in,Compact,Marker,Table,Inline-table,Table-row-group,Table-header-group,Table-footer-group,Table-row,Table-column-group,Table-column,Table-cell,Table-caption", "default_value"=>-1, "pvalues"=>"inline,none,block,list-item,run-in,compact,marker,table,inline-table,table-row-group,table-header-group,table-footer-group,table-row,table-column-group,table-column,table-cell,table-caption", "punits"=>"", "title"=>"display", "id"=>11, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"None,Left,Right", "default_value"=>0, "pvalues"=>"none,left,right", "punits"=>"", "title"=>"float", "id"=>12, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Static,Relative,Absolute,Fixed", "default_value"=>0, "pvalues"=>"static,relative,absolute,fixed", "punits"=>"", "title"=>"position", "id"=>13, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Visible,Hidden,Collapse", "default_value"=>0, "pvalues"=>"visible,hidden,collapse", "punits"=>"", "title"=>"visibility", "id"=>14, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Auto,L1", "default_value"=>0, "pvalues"=>"auto,l1", "punits"=>"l,%", "title"=>"height", "id"=>15, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Normal,L1", "default_value"=>0, "pvalues"=>"normal,l1", "punits"=>"l,%,f", "title"=>"line-height", "id"=>16, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"None,L1", "default_value"=>0, "pvalues"=>"none,l1", "punits"=>"l,%", "title"=>"max-height", "id"=>17, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"None,L1", "default_value"=>0, "pvalues"=>"none,l1", "punits"=>"l,%", "title"=>"max-width", "id"=>18, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"L1", "default_value"=>0, "pvalues"=>"l1", "punits"=>"l,%", "title"=>"min-height", "id"=>19, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"L1", "default_value"=>-1, "pvalues"=>"l1", "punits"=>"l,%", "title"=>"min-width", "id"=>20, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Auto,L1", "default_value"=>0, "pvalues"=>"auto,l1", "punits"=>"l,%", "title"=>"width", "id"=>21, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Caption,Icon,Menu,Message-box,Small-caption,Status-bar", "default_value"=>0, "pvalues"=>"caption,icon,menu,message-box,small-caption,status-bar", "punits"=>"", "title"=>"font", "id"=>22, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"Serif,Sans-serif", "default_value"=>0, "pvalues"=>"serif,sans-serif", "punits"=>"", "title"=>"font-family", "id"=>23, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"L1", "default_value"=>0, "pvalues"=>"l1", "punits"=>"%,em", "title"=>"font-size", "id"=>24, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"Normal,Italic,Oblique", "default_value"=>0, "pvalues"=>"normal,italic,oblique", "punits"=>"", "title"=>"font-style", "id"=>25, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"Normal,Small-caps", "default_value"=>0, "pvalues"=>"normal,small-caps", "punits"=>"", "title"=>"font-variant", "id"=>26, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"Normal,Bold,Bolder,Lighter,100,200,300,400,500,600,700,800,900", "default_value"=>0, "pvalues"=>"normal,bold,bolder,lighter,100,200,300,400,500,600,700,800,900", "punits"=>"", "title"=>"font-weight", "id"=>27, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"None,0i", "default_value"=>0, "pvalues"=>"none,0i", "punits"=>"", "title"=>"list-style-image", "id"=>28, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"Outside,Inside", "default_value"=>-1, "pvalues"=>"outside,inside", "punits"=>"", "title"=>"list-style-position", "id"=>29, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"Disc,None,Circle,Square,Decimal,Decimal-leading-zero,Lower-roman,Upper-roman,Lower-alpha,Upper-alpha,Lower-greek,Lower-latin,Upper-latin,Hebrew,Armenian,Georgian,Cjk-ideographic,Hiragana,Katakana,Hiragana-iroha,Katakana-iroha", "default_value"=>-1, "pvalues"=>"disc,none,circle,square,decimal,decimal-leading-zero,lower-roman,upper-roman,lower-alpha,upper-alpha,lower-greek,lower-latin,upper-latin,hebrew,armenian,georgian,cjk-ideographic,hiragana,katakana,hiragana-iroha,katakana-iroha", "punits"=>"", "title"=>"list-style-type", "id"=>30, "pvspecial"=>"inherit"},
  {"neg_ok"=>true, "pvalues_desc"=>"Auto,L1", "default_value"=>0, "pvalues"=>"auto,l1", "punits"=>"l,%", "title"=>"margin", "id"=>31, "pvspecial"=>"trbl"},
  {"neg_ok"=>false, "pvalues_desc"=>"L1", "default_value"=>0, "pvalues"=>"l1", "punits"=>"l,%", "title"=>"padding", "id"=>32, "pvspecial"=>"trbl"},
  {"neg_ok"=>true, "pvalues_desc"=>"Auto,L1", "default_value"=>0, "pvalues"=>"auto,l1", "punits"=>"l,%", "title"=>"bottom", "id"=>33, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Auto,0r", "default_value"=>0, "pvalues"=>"auto,0r", "punits"=>"", "title"=>"clip", "id"=>34, "pvspecial"=>""},
  {"neg_ok"=>true, "pvalues_desc"=>"Auto,L1", "default_value"=>0, "pvalues"=>"auto,l1", "punits"=>"l,%", "title"=>"left", "id"=>35, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Visible,Hidden,Scroll,Auto", "default_value"=>0, "pvalues"=>"visible,hidden,scroll,auto", "punits"=>"", "title"=>"overflow", "id"=>36, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Visible,Hidden,Scroll,Auto", "default_value"=>0, "pvalues"=>"visible,hidden,scroll,auto", "punits"=>"", "title"=>"overflow-x", "id"=>37, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Visible,Hidden,Scroll,Auto", "default_value"=>0, "pvalues"=>"visible,hidden,scroll,auto", "punits"=>"", "title"=>"overflow-y", "id"=>38, "pvspecial"=>""},
  {"neg_ok"=>true, "pvalues_desc"=>"Auto,L1", "default_value"=>0, "pvalues"=>"auto,l1", "punits"=>"l,%", "title"=>"right", "id"=>40, "pvspecial"=>""},
  {"neg_ok"=>true, "pvalues_desc"=>"Auto,L1", "default_value"=>0, "pvalues"=>"auto,l1", "punits"=>"l,%", "title"=>"top", "id"=>41, "pvspecial"=>""},
  {"neg_ok"=>true, "pvalues_desc"=>"Baseline,Sub,Super,Top,Text-top,Middle,Bottom,Text-bottom,L1", "default_value"=>0, "pvalues"=>"baseline,sub,super,top,text-top,middle,bottom,text-bottom,l1", "punits"=>"l,%", "title"=>"vertical-align", "id"=>42, "pvspecial"=>""},
  {"neg_ok"=>true, "pvalues_desc"=>"Auto,L1", "default_value"=>0, "pvalues"=>"auto,l1", "punits"=>"", "title"=>"z-index", "id"=>43, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Collapse,Separate", "default_value"=>-1, "pvalues"=>"collapse,separate", "punits"=>"", "title"=>"border-collapse", "id"=>44, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"L2", "default_value"=>-1, "pvalues"=>"l2", "punits"=>"l", "title"=>"border-spacing", "id"=>45, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"Top,Bottom,Left,Right", "default_value"=>0, "pvalues"=>"top,bottom,left,right", "punits"=>"", "title"=>"caption-side", "id"=>46, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Hide,Show", "default_value"=>0, "pvalues"=>"hide,show", "punits"=>"", "title"=>"empty-cells", "id"=>47, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Auto,Fixed", "default_value"=>0, "pvalues"=>"auto,fixed", "punits"=>"", "title"=>"table-layout", "id"=>48, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Aqua,Black,Blue,Fuchsia,Gray,Green,Lime,Maroon,Navy,Olive,Purple,Red,Silver,Teal,White,Yellow,0c", "default_value"=>-1, "pvalues"=>"aqua,black,blue,fuchsia,gray,green,lime,maroon,navy,olive,purple,red,silver,teal,white,yellow,0c", "punits"=>"", "title"=>"color", "id"=>49, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"Ltr,Rtl", "default_value"=>-1, "pvalues"=>"ltr,rtl", "punits"=>"", "title"=>"direction", "id"=>50, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"None,Hidden,Double,Solid,Dashed,Dotted,Ridge,Outset,Groove,Inset", "default_value"=>0, "pvalues"=>"none,hidden,double,solid,dashed,dotted,ridge,outset,groove,inset", "punits"=>"", "title"=>"border-style", "id"=>51, "pvspecial"=>"trbl"},
  {"neg_ok"=>true, "pvalues_desc"=>"Normal,L1", "default_value"=>0, "pvalues"=>"normal,l1", "punits"=>"l", "title"=>"letter-spacing", "id"=>52, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"Left,Right,Center,Justify", "default_value"=>0, "pvalues"=>"left,right,center,justify", "punits"=>"", "title"=>"text-align", "id"=>53, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"None,Underline,Overline,Line-through,Blink", "default_value"=>0, "pvalues"=>"none,underline,overline,line-through,blink", "punits"=>"", "title"=>"text-decoration", "id"=>54, "pvspecial"=>""},
  {"neg_ok"=>true, "pvalues_desc"=>"L1", "default_value"=>0, "pvalues"=>"l1", "punits"=>"l,%", "title"=>"text-indent", "id"=>55, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"None,Capitalize,Uppercase,Lowercase", "default_value"=>0, "pvalues"=>"none,capitalize,uppercase,lowercase", "punits"=>"", "title"=>"text-transform", "id"=>56, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"Normal,Pre,Nowrap", "default_value"=>0, "pvalues"=>"normal,pre,nowrap", "punits"=>"", "title"=>"white-space", "id"=>57, "pvspecial"=>"inherit"},
  {"neg_ok"=>true, "pvalues_desc"=>"Normal,L1", "default_value"=>0, "pvalues"=>"normal,l1", "punits"=>"l", "title"=>"word-spacing", "id"=>58, "pvspecial"=>"inherit"},
  {"neg_ok"=>false, "pvalues_desc"=>"L1", "default_value"=>-1, "pvalues"=>"l1", "punits"=>"px", "title"=>"width", "id"=>59, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Href", "default_value"=>0, "pvalues"=>"0u", "punits"=>"", "title"=>"href", "id"=>60, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Src", "default_value"=>0, "pvalues"=>"0i", "punits"=>"", "title"=>"src", "id"=>61, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Alt", "default_value"=>0, "pvalues"=>"0t", "punits"=>"", "title"=>"alt", "id"=>62, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Href", "default_value"=>-1, "pvalues"=>"0u", "punits"=>"", "title"=>"href", "id"=>63, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"", "default_value"=>-1, "pvalues"=>"", "punits"=>"", "title"=>"layout db", "id"=>64, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0t", "default_value"=>-1, "pvalues"=>"0t", "punits"=>"", "title"=>"layout string", "id"=>65, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0i", "default_value"=>-1, "pvalues"=>"0i", "punits"=>"", "title"=>"layout themeimg", "id"=>66, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0b", "default_value"=>-1, "pvalues"=>"0b", "punits"=>"", "title"=>"layout bool", "id"=>67, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"", "default_value"=>-1, "pvalues"=>"", "punits"=>"", "title"=>"layout int", "id"=>68, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0t", "default_value"=>-1, "pvalues"=>"0t", "punits"=>"", "title"=>"themenable var", "id"=>69, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"", "default_value"=>-1, "pvalues"=>"", "punits"=>"", "title"=>"themenable db", "id"=>70, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0t", "default_value"=>-1, "pvalues"=>"0t", "punits"=>"", "title"=>"themenable string", "id"=>71, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0i", "default_value"=>-1, "pvalues"=>"0i", "punits"=>"", "title"=>"themenable themeimg", "id"=>72, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0b", "default_value"=>-1, "pvalues"=>"0b", "punits"=>"", "title"=>"themenable bool", "id"=>73, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"", "default_value"=>-1, "pvalues"=>"", "punits"=>"", "title"=>"themenable int", "id"=>74, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0fluid,1fixedcentered,2fixed", "default_value"=>-1, "pvalues"=>"0fluid,1fixedcentered,2fixed", "punits"=>"", "title"=>"body-width-style", "id"=>75, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"None,Hidden,Dotted,Dashed,Solid,Double,Groove,Ridge,Inset,Outset", "default_value"=>0, "pvalues"=>"none,hidden,dotted,dashed,solid,double,groove,ridge,inset,outset", "punits"=>"", "title"=>"border-style", "id"=>76, "pvspecial"=>"trbl"},
  {"neg_ok"=>false, "pvalues_desc"=>"L1", "default_value"=>-1, "pvalues"=>"l1", "punits"=>"", "title"=>"border-width", "id"=>77, "pvspecial"=>"trbl"},
  {"neg_ok"=>false, "pvalues_desc"=>"L1", "default_value"=>0, "pvalues"=>"l1", "punits"=>"l,%", "title"=>"width", "id"=>78, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"L1", "default_value"=>0, "pvalues"=>"l1", "punits"=>"l,%", "title"=>"height", "id"=>79, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"", "default_value"=>-1, "pvalues"=>"", "punits"=>"", "title"=>"Heading", "id"=>80, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"", "default_value"=>-1, "pvalues"=>"", "punits"=>"", "title"=>"Heading", "id"=>81, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0t", "default_value"=>-1, "pvalues"=>"0t", "punits"=>"", "title"=>"content var", "id"=>82, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Please select a menu", "default_value"=>-1, "pvalues"=>"0d", "punits"=>"", "title"=>"db", "id"=>83, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0t", "default_value"=>-1, "pvalues"=>"0t", "punits"=>"", "title"=>"text", "id"=>84, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0i", "default_value"=>-1, "pvalues"=>"0i", "punits"=>"", "title"=>"content themeimg", "id"=>85, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0b", "default_value"=>-1, "pvalues"=>"0b", "punits"=>"", "title"=>"horizontal", "id"=>86, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"", "default_value"=>-1, "pvalues"=>"", "punits"=>"", "title"=>"content int", "id"=>87, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0t", "default_value"=>-1, "pvalues"=>"0t", "punits"=>"", "title"=>"area var", "id"=>88, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"", "default_value"=>-1, "pvalues"=>"", "punits"=>"", "title"=>"area db", "id"=>89, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0t", "default_value"=>-1, "pvalues"=>"0t", "punits"=>"", "title"=>"area string", "id"=>90, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0i", "default_value"=>-1, "pvalues"=>"0i", "punits"=>"", "title"=>"area themeimg", "id"=>91, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0b", "default_value"=>0, "pvalues"=>"0b", "punits"=>"", "title"=>"fixed", "id"=>92, "pvspecial"=>""},
    #fixed or fluid of the page layout
  {"neg_ok"=>false, "pvalues_desc"=>"", "default_value"=>-1, "pvalues"=>"", "punits"=>"", "title"=>"area int", "id"=>93, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0s", "default_value"=>-1, "pvalues"=>"0s", "punits"=>"", "title"=>"content sections", "id"=>94, "pvspecial"=>""},
  {"neg_ok"=>true, "pvalues_desc"=>"L1", "default_value"=>-1, "pvalues"=>"l1", "punits"=>"l,%", "title"=>"margin-top", "id"=>95, "pvspecial"=>""},
  {"neg_ok"=>true, "pvalues_desc"=>"Auto,L1", "default_value"=>-1, "pvalues"=>"auto,l1", "punits"=>"l,%", "title"=>"margin-right", "id"=>96, "pvspecial"=>""},
  {"neg_ok"=>true, "pvalues_desc"=>"L1", "default_value"=>-1, "pvalues"=>"l1", "punits"=>"l,%", "title"=>"margin-bottom", "id"=>97, "pvspecial"=>""},
  {"neg_ok"=>true, "pvalues_desc"=>"Auto,L1", "default_value"=>-1, "pvalues"=>"auto,l1", "punits"=>"l,%", "title"=>"margin-left", "id"=>98, "pvspecial"=>""},
  {"neg_ok"=>true, "pvalues_desc"=>"1", "default_value"=>-1, "pvalues"=>"1", "punits"=>"", "title"=>"content sections", "id"=>99, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Auto,100%,L1", "default_value"=>-1, "pvalues"=>"auto,100%,l1", "punits"=>"px", "title"=>"width", "id"=>100, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Left,Right", "default_value"=>-1, "pvalues"=>"left,right", "punits"=>"", "title"=>"float", "id"=>101, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Basic,Stardard list,Snapshot", "default_value"=>-1, "pvalues"=>"basic,stardard_list,snapshot", "punits"=>"", "title"=>"list_style", "id"=>102, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"List,Ggrid,Grid", "default_value"=>-1, "pvalues"=>"list,ggrid,grid", "punits"=>"", "title"=>"list_style", "id"=>103, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0,1", "default_value"=>-1, "pvalues"=>"0,1", "punits"=>"", "title"=>"layout_style", "id"=>104, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0u", "default_value"=>-1, "pvalues"=>"0U", "punits"=>"", "title"=>"url", "id"=>105, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"0,1", "default_value"=>-1, "pvalues"=>"0,1", "punits"=>"", "title"=>"radio_hv", "id"=>106, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"No-repeat,Repeat-x,Repeat-y", "default_value"=>0, "pvalues"=>"no-repeat,repeat-x,repeat-y", "punits"=>"", "title"=>"background-repeat", "id"=>107, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"L1", "default_value"=>0, "pvalues"=>"l1", "punits"=>"l,%", "title"=>"padding-left", "id"=>108, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"L1", "default_value"=>0, "pvalues"=>"l1", "punits"=>"l,%", "title"=>"padding-right", "id"=>109, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"L1", "default_value"=>-1, "pvalues"=>"l1", "punits"=>"l", "title"=>"padding", "id"=>110, "pvspecial"=>"trbl"},
  {"neg_ok"=>true, "pvalues_desc"=>"L1", "default_value"=>0, "pvalues"=>"l1", "punits"=>"l", "title"=>"margin", "id"=>111, "pvspecial"=>"trbl"},
  {"neg_ok"=>false, "pvalues_desc"=>"0i", "default_value"=>0, "pvalues"=>"0i", "punits"=>"", "title"=>"background-image", "id"=>112, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Repeat-y,No-repeat", "default_value"=>-1, "pvalues"=>"repeat-y,no-repeat", "punits"=>"", "title"=>"background-repeat", "id"=>113, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"Repeat-x,No-repeat", "default_value"=>-1, "pvalues"=>"repeat-x,no-repeat", "punits"=>"", "title"=>"background-repeat", "id"=>114, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"", "default_value"=>-1, "pvalues"=>"", "punits"=>"", "title"=>"composite", "id"=>115, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"1,0", "default_value"=>-1, "pvalues"=>"1,0", "punits"=>"", "title"=>"sitemap_view_style", "id"=>116, "pvspecial"=>""},
  {"neg_ok"=>false, "pvalues_desc"=>"1809,1810,1811,1812,1813", "default_value"=>1, "pvalues"=>"1809,1810,1811,1812,1813", "punits"=>"", "title"=>"composite", "id"=>117, "pvspecial"=>""}]

HtmlAttribute.delete_all              
for ha in objs
  obj = HtmlAttribute.new
  obj.assign_attributes( ha,  :without_protection => true)
  obj.save
end
                
